# ========================================================================
# Master Application Configuration
# ========================================================================
spring.application.name=projectj
server.port=8080

# Activate local profile by default for local development
spring.profiles.active=local

# JPA Settings
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT default expiration (10 minutes)
jwt.expiration=86400000

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

spring.data.redis.ssl.enabled=true
spring.data.redis.timeout=5s